translate:
  image: icr.io/ai-services-cicd/translate-service:v0.0.7
  log_level: "INFO"
  database: "translate_metadata"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-4
  storage: 5Gi
  # @generate:password
  password: ""

