extract:
  image: icr.io/ai-services-cicd/extract-service:v0.0.11
  log_level: "INFO"
  database: "extract_metadata"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-4
  storage: 5Gi
  # @generate:password
  password: ""

