summarize:
  port: ""
  image: icr.io/ai-services-cicd/summarize-service:v0.0.19
  log_level: "INFO"
  database: "summarize_metadata"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-5
  username: "postgres"
  # @generate:password
  password: ""

mcp:
  image: icr.io/ai-services-cicd/ai-services-mcp:v0.0.1
  port: "6001"
# Made with Bob
