summarize:
  image: icr.io/ai-services-cicd/summarize-service:v0.0.19
  log_level: "INFO"
  database: "summarize_metadata"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

postgres:
  image: icr.io/ai-services-cicd/postgres:18-5
  storage: 5Gi
  # @generate:password
  password: ""

