similarity:
  image: icr.io/ai-services-cicd/similarity-service:v0.0.13
  log_level: "INFO"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

embedding:
  model:
    name: ""
    maxModelLen: 512

reranker:
  model:
    name: ""
