embedding:
  image: icr.io/ai-services-cicd/embedding-service:v1.0.0
  log_level: "INFO"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

model:
  name: ""
