{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "catalog-db-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "catalog-db-secret"
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: database
type: Opaque
stringData:
  db-password: {{ if $existingSecret }}{{ index $existingSecret.data "db-password" | b64dec | quote }}{{ else }}{{ .Values.db.password | quote }}{{ end }}
