{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "catalog-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "catalog-secret"
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: catalog
type: Opaque
stringData:
  admin-password: {{ if $existingSecret }}{{ index $existingSecret.data "admin-password" | b64dec | quote }}{{ else }}{{ .Values.backend.adminPasswordHash | quote }}{{ end }}
