{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "catalog-db-encryption-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "catalog-db-encryption-secret"
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
    ai-services.io/component: catalog
type: Opaque
stringData:
  db-encryption-key: {{ if $existingSecret }}{{ index $existingSecret.data "db-encryption-key" | b64dec | quote }}{{ else }}{{ .Values.backend.dbEncryptionKey | quote }}{{ end }}
